server:
  port: 8000

spring:
  application:
    name: gateway
    
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      serviceId: multiplication
      strip-prefix: false
    results:
      path: /results/**
      serviceId: multiplication
      strip-prefix: false
    leaders:
      path: /leaders/**
      serviceId: gamification
      strip-prefix: false
    stats:
      path: /stats/**
      serviceId: gamification
      strip-prefix: false
      
management:
  endpoints:
    web:
      exposure:
        include: httptrace, routes
eureka:
  enabled: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    