server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: multiplications
        uri: lb://multiplication
        predicates:
        - Path=/api/multiplications/**
        filters:
        - name: CircuitBreaker
          args:
            name: multiplicationsCircuitBreaker
            fallbackUri: forward:/multiplications-fallback
        - StripPrefix=1
      - id: results
        uri: lb://multiplication
        predicates:
        - Path=/api/results/**
        filters:
        - StripPrefix=1
      - id: leaders
        uri: lb://gamification
        predicates:
        - Path=/api/leaders/**
        filters:
        - StripPrefix=1
      - id: stats
        uri: lb://gamification
        predicates:
        - Path=/api/stats/**
        filters:
        - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: httptrace, gateway
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka
